name: Update Changelog

on:
  push:
    tags:
      - 'v*'

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Récupère tout l'historique
    
    - name: Generate Changelog
      uses: mikepenz/release-changelog-builder-action@v4
      with:
        configuration: ".github/changelog-config.json"
        outputFile: "CHANGELOG.md"
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Commit Updated Changelog
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add CHANGELOG.md
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "docs: update CHANGELOG.md for ${{ github.ref_name }}"
          git push
        fi