name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags that start with 'v'
    branches:
      - main  # Only on main branch

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install uv
      run: pip install uv
    
    - name: Install dependencies
      run: uv sync
    
    - name: Update version from tag
      run: |
        TAG_VERSION=${GITHUB_REF#refs/tags/v}
        sed -i "s/version = \".*\"/version = \"$TAG_VERSION\"/" pyproject.toml
    
    - name: Build package
      run: uv build
    
    - name: Publish to PyPI
      run: uv publish --token ${{ secrets.PYPI_TOKEN }} dist/*